CREATE TYPE star_rating AS ENUM ('1', '2', '3', '4', '5');
--The table should contain fields for id, title, url, description and rating
CREATE TABLE bookmarks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  rating star_rating NOT NULL,
  description TEXT
);
--description is the only optional field